apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-07-18T22:54:12Z"
  generation: 2
  labels:
    app: book-service
  name: book-service
  namespace: default
  resourceVersion: "1264"
  uid: bbdfdff6-1495-4eb5-b5ae-f62bb2521af9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: book-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: book-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/book_service
          image: leandrocgsi/book-service:kube-v1
          imagePullPolicy: IfNotPresent
          name: book-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-07-18T22:54:41Z"
      lastUpdateTime: "2025-07-18T22:54:41Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-07-18T22:54:12Z"
      lastUpdateTime: "2025-07-18T22:54:42Z"
      message: ReplicaSet "book-service-5998b6889b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-07-18T22:55:08Z"
  labels:
    app: book-service
  name: book-service
  namespace: default
  resourceVersion: "1306"
  uid: 8f842b1e-1344-4239-886b-96018472637a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.34.210
  clusterIPs:
    - 10.106.34.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32330
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: book-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: localhost
