apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2026-01-08T11:43:05Z"
  generation: 2
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
  resourceVersion: "284438"
  uid: 970362bc-177a-4671-a3c4-92384a4589d3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: exchange-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/exchange_service
          image: codedemonbr/exchange-service:kube-v1
          imagePullPolicy: IfNotPresent
          name: exchange-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2026-01-08T11:43:05Z"
      lastUpdateTime: "2026-01-08T11:47:17Z"
      message: ReplicaSet "exchange-service-7644c45f98" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-08T11:55:10Z"
      lastUpdateTime: "2026-01-08T11:55:10Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-01-08T11:49:24Z"
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
  resourceVersion: "283869"
  uid: c6a246d3-d47e-4a93-9de5-8c4b04b73c8e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.28.133
  clusterIPs:
    - 10.103.28.133
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30323
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: exchange-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: localhost
