name: Microservices Continous Deployment with GIthub Actions

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build Eureka Naming Server Docker Image
        working-directory: ./naming-server
        run: mvn clean package

      - name: Build API Gateway Docker Image
        working-directory: ./api-gateway
        run: mvn clean package

      - name: Build Exchange Microservice Docker Image
        working-directory: ./exchange-service
        run: mvn clean package

      - name: Build Book Microservice Docker Image
        working-directory: ./book-service
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Tag Docker Images
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/naming-server:latest ${{secrets.DOCKER_USERNAME}}/naming-server:${{github.RUN_ID}}
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:latest ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.RUN_ID}}
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
          docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}
