name: Microservices Continous Deployment with GIthub Actions

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build Exchange Microservice Docker Image
        working-directory: ./exchange-service
        run: mvn clean package

      - name: Build Book Microservice Docker Image
        working-directory: ./book-service
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Tag Docker Images
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
          docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}
          docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:kube-v1

      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
          docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:kube-v1
          docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}

      - uses: "google-github-actions/auth@v3"
        with:
          project_id: "project-02667c71-8bca-40e2-a62"
          workload_identity_provider: "projects/73702852560/locations/global/workloadIdentityPools/github"
